BTreeDB/urls.py
from django.urls import path
from . import views

app_name = 'BTreeDB'
urlpatterns = [
    # Main page
    path('', views.index, name='index')
]

BTreeDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('btree_app.urls')),
]

btree_db/urls.py
from django.urls import path
from . import views

app_name = 'btree_db'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert/', views.insert, name='insert'),
    path('inserted/', views.inserted, name='inserted'),
    path('update/', views.update, name='update'),
    path('updated/', views.updated, name='updated'),
    path('delete/', views.delete, name='delete'),
    path('deleted/', views.deleted, name='deleted'),
    path('read/', views.read, name='read'),
    path('view/<int:key>', views.view, name='view'),
    path('delete_all/', views.delete_all, name='delete_all'),
    path('view_all/', views.view_all, name='view_all'),
]

btree_db/forms.py
from django.forms import Form, IntegerField, CharField, Textarea, NumberInput, ValidationError
from .db.db_operations import init_db


class KeyValueForm(Form):
    key = IntegerField(label='', min_value=0, max_value=2 ** 32 - 1, widget=NumberInput({'placeholder': 'Key'}))
    value = CharField(label='', max_length=2 ** 16 - 1, widget=Textarea({'placeholder': 'Value', 'rows': 5}))


class KeyForm(Form):
    key = IntegerField(label='', min_value=0, widget=NumberInput({'placeholder': 'Key'}))


class KeyExistsForm(Form):

    def clean_key(self):
        key = int(self.cleaned_data['key'])
        btree = init_db(False)
        with btree.open('r'):
            try:
                btree[key]
            except KeyError:
                return key
            else:
                raise ValidationError('Key already exists')


class KeyDoesntExistForm(Form):

    def clean_key(self):
        key = int(self.cleaned_data['key'])
        btree = init_db(False)
        with btree.open('r'):
            try:
                btree[key]
            except KeyError:
                raise ValidationError("Key doesn't exists")
            else:
                return key


class InsertForm(KeyValueForm, KeyExistsForm):
    pass


class UpdateForm(KeyValueForm, KeyDoesntExistForm):
    pass


class DeleteForm(KeyForm, KeyDoesntExistForm):
    pass


class ReadForm(KeyForm, KeyDoesntExistForm):
    pass

btree_db/views.py
from django.shortcuts import render, redirect
from .forms import InsertForm, UpdateForm, DeleteForm, ReadForm
from .db import db_operations


def index(request):
    context = {'form': ''}
    return render(request, 'btree_db/index.html', context)


def insert(request):
    if request.method == 'POST':
        form = InsertForm(data=request.POST)
        if form.is_valid():
            db_operations.insert_or_update(form.data)
            return redirect('btree_db:inserted')
    else:
        form = InsertForm()

    context = {'form': form}
    return render(request, 'btree_db/insert.html', context)


def inserted(request):
    return render(request, 'btree_db/inserted.html')


def update(request):
    if request.method == 'POST':
        form = UpdateForm(data=request.POST)
        if form.is_valid():
            db_operations.insert_or_update(form.data)
            return redirect('btree_db:updated')
    else:
        form = UpdateForm()

    context = {'form': form}
    return render(request, 'btree_db/update.html', context)


def updated(request):
    return render(request, 'btree_db/updated.html')


def delete(request):
    if request.method == 'POST':
        form = DeleteForm(data=request.POST)
        if form.is_valid():
            db_operations.delete(form.data)
            return redirect('btree_db:deleted')
    else:
        form = DeleteForm()

    context = {'form': form}
    return render(request, 'btree_db/delete.html', context)


def deleted(request):
    return render(request, 'btree_db/deleted.html')


def delete_all(request):
    db_operations.delete_all()
    return render(request, 'btree_db/deleted_all.html')


def read(request):
    if request.method == 'POST':
        form = ReadForm(data=request.POST)
        if form.is_valid():
            return redirect('btree_db:view', key=form.data['key'])
    else:
        form = ReadForm()

    context = {'form': form}
    return render(request, 'btree_db/read.html', context)


def view(request, key):
    value = db_operations.read({'key': key})
    context = {'value': value, 'key': key}
    return render(request, 'btree_db/view.html', context)


def view_all(request):
    data = db_operations.read_all()
    context = {'data': data}
    return render(request, 'btree_db/view_all.html', context)

templates/btree_db/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>B-Tree Database</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <header>
        <div class="px-4 py-2 bg-dark">
            <div class="d-flex">
                <h1>
                    <a class="text-decoration-none text-white" href="{% url 'btree_db:index' %}">B-Tree Database</a>
                </h1>
            </div>
        </div>
    </header>
    <main>
        <section class="px-4 py-2 border-bottom">
            {% block pageheader %}{% endblock pageheader %}
        </section>
        <section class="px-4 py-2">
            {% block content %}{% endblock content %}
        </section>
    </main>
</body>
</html>

templates/btree_db/delete.html
{% extends 'btree_db/base.html' %}

{% block pageheader %}
    <h2>Delete a record in the database</h2>
{% endblock pageheader %}

{% block content %}
    {% url 'btree_db:delete' as url %}
    {% include 'btree_db/form.html' with url=url form=form %}
{% endblock content %}

templates/btree_db/insert.html
{% extends 'btree_db/base.html' %}

{% block pageheader %}
    <h2>Insert a record into the database</h2>
{% endblock pageheader %}

{% block content %}
    {% url 'btree_db:insert' as url %}
    {% include 'btree_db/form.html' with url=url form=form %}
{% endblock content %}

templates/btree_db/read.html
{% extends 'btree_db/base.html' %}

{% block pageheader %}
    <h2>Read a record from the database</h2>
{% endblock pageheader %}

{% block content %}
    {% url 'btree_db:read' as url %}
    {% include 'btree_db/form.html' with url=url form=form %}
{% endblock content %}

templates/btree_db/update.html
{% extends 'btree_db/base.html' %}

{% block pageheader %}
    <h2>Update a record in the database</h2>
{% endblock pageheader %}

{% block content %}
    {% url 'btree_db:update' as url %}
    {% include 'btree_db/form.html' with url=url form=form %}
{% endblock content %}

templates/btree_db/view.html
{% extends 'btree_db/base.html' %}

{% block pageheader %}
    <h3>View a database record</h3>
{% endblock pageheader %}

{% block content %}
    <h4>
        <span class="text-secondary">Key:</span> <span style="overflow-wrap: break-word;">{{ key }}</span>
    </h4>
    <h4>
        <span class="text-secondary">Value:</span> <span style="overflow-wrap: break-word;">{{ value }}</span>
    </h4>
    <a class="btn btn-primary my-2" role="button" href="{% url 'btree_db:index' %}">Back</a>
{% endblock content %}

templates/btree_db/view_all.html
{% extends 'btree_db/base.html' %}

{% block pageheader %}
    <h3>View all database records</h3>
{% endblock pageheader %}

{% block content %}
    {% if data %}
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">Key</th>
                    <th scope="col">Value</th>
                </tr>
            </thead>
            <tbody>
                {% for key, value in data %}
                    <tr>
                        <td style="max-width:20px; overflow-wrap: break-word;">{{ key }}</td>
                        <td style="max-width:80px; overflow-wrap: break-word;">{{ value }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Database is empty</p>
        <a class="btn btn-primary" role="button" href={% url 'btree_db:insert' %}>Insert records</a>
    {% endif %}
{% endblock %}